# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktree < Formula
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_darwin_amd64.tar.gz"
      sha256 "77be6e48a5cad17d72b5a517636ad7a2704cb46b4ab70452fdb0f8cf8863e10a"

      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_darwin_arm64.tar.gz"
      sha256 "1805faf968147109a3c2c8813df9bb681fc95fecbb9b24934a5e20c0bd836483"

      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_linux_amd64.tar.gz"
      sha256 "8a2bd2794f4576518d6f72b1986ddb223cf8c2974c04bea16ab6f7820c3c078f"
      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_linux_arm64.tar.gz"
      sha256 "d49753e146b2bcc07c6bd489e8d344d8981734cff14d8ddd9de205c0af8a2bff"
      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  test do
    system "#{bin}/ktree", "--init-shell", "bash"
  end
end
