# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktree < Formula
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_darwin_amd64.tar.gz"
      sha256 "8f7ebcce115f4bd984842a89f16e410ecdb4c25c4d0f7b03b75d757970813882"

      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_darwin_arm64.tar.gz"
      sha256 "331c5724cc42f6a6a9928d8ba63783cd2eb1038f2382a8f3731f937d57d799bf"

      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_linux_amd64.tar.gz"
      sha256 "4862315d50752892c866fe9be94887605d1bc6ecb734768274529349b745f55e"
      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.1.0/ktree_linux_arm64.tar.gz"
      sha256 "129fa0ff32a2a769a480620c75269e5494318488effe16bb861fce878dc59059"
      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  test do
    system "#{bin}/ktree", "--init-shell", "bash"
  end
end
