# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktree" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "7a963d1a38c223dfe54bcfd0c8733747ee0085cf2b1f16a62c00ac2b1aaed51a"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8bcf7344bd17c7cf4d85cc7f0a6bae9812cc184252472d7193f314a561886fd"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2f123d1761c396cc28721eab0d0a7dd89cb9be9f1e7e38ac0b7753932927f0e"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba8cfcbcdc7b111426cd672b28815a1418c34caea83ba15421ae846df20b6a1b"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_arm64.tar.gz"
    end
  end

  name "ktree"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktree"

  # No zap stanza required

end
