# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktree" do
  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "5d9eb972f2be6366129ddb5f583e4288b67e66d2895d42cb8cea5c78cb1fab83"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef011b59736ed27145136e811a8985400c1b80e029ccab2f1a9e9da6fd0985cd"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd548bf768cd56a50a81f81b7010414c8d3fc462ff1377543b1882cacd8332da"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "434cb43a2c8fb66290ba79bfc032814ed4c9f5a0b493a276dcfd5079d8f94b38"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_amd64.tar.gz"
    end
  end

  name "ktree"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktree"

  # No zap stanza required
end
