# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktree" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "94596ee1b02979da5fab13f79221075ce6250e8aa1472290604bedc6f9994f78"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "939c0f2e52da8017a398d1b0f74a99657ad0cae64b8a3c4af3dbd78dfdbfd78d"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5998d4f6c4798bb5680a282d0fa4be35fadfd34f4d5e55ab496bc224a954da91"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef8e09b7b331852408ab6aeede77a40be79750c4d58351a050bbeb5b68d36fa2"
      url "https://github.com/alikazai/ktree/releases/download/v#{version}/ktree_linux_amd64.tar.gz"
    end
  end

  name "ktree"
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktree"

  # No zap stanza required
end
