# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktree < Formula
  desc "Terminal UI for managing git worktrees"
  homepage "https://github.com/alikazai/ktree"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikazai/ktree/releases/download/v0.2.0/ktree_darwin_amd64.tar.gz"
      sha256 "948bfcaa9e035455df3fb9023d634877c25190dd52531117fadf848591bc4e9f"

      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikazai/ktree/releases/download/v0.2.0/ktree_darwin_arm64.tar.gz"
      sha256 "70accc5f60df7962751f0fe4e6e9936064a3be8aaa3daaf1d85b55682684b8a2"

      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.2.0/ktree_linux_amd64.tar.gz"
      sha256 "7aa67c367301bf9696bb74ed29452003813fab49a91ad307a840ad143eb257cd"
      define_method(:install) do
        bin.install "ktree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikazai/ktree/releases/download/v0.2.0/ktree_linux_arm64.tar.gz"
      sha256 "6cca278ce4fff82f28f8cdb71137177c356b264ff3cebc22684ee685ff55d787"
      define_method(:install) do
        bin.install "ktree"
      end
    end
  end

  test do
    system "#{bin}/ktree", "--init-shell", "bash"
  end
end
